version: '3.0'

services:
  grafana:
    container_name: 'lesly-uploadfile-app'
    platform: 'linux/amd64'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-10.0.3}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/lesly-uploadfile-app
      - ./provisioning:/etc/grafana/provisioning
    environment:
      # - GF_INSTALL_PLUGINS=http://${GF_PLUGIN_UPLOAD_IPHOST}:9997/static/archives/lesly-smartfactory-app.zip;lesly-smartfactory-app
      - GF_PLUGIN_UPLOAD_IPHOST=${GF_PLUGIN_UPLOAD_IPHOST}
      - GF_PLUGIN_UPLOAD_DBHOST=${GF_PLUGIN_UPLOAD_DBHOST}
      - GF_PLUGIN_UPLOAD_LESLYHOST=${GF_PLUGIN_UPLOAD_LESLYHOST}
